services:
  - type: web
    name: medicine-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y gfortran
      pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT